function Readability(uri,doc,options){options=options||{};this._uri=uri;this._doc=doc;this._articleTitle=null;this._articleByline=null;this._articleDir=null;this._attempts=[];this._debug=!!options.debug;this._maxElemsToParse=options.maxElemsToParse||this.DEFAULT_MAX_ELEMS_TO_PARSE;this._nbTopCandidates=options.nbTopCandidates||this.DEFAULT_N_TOP_CANDIDATES;this._charThreshold=options.charThreshold||this.DEFAULT_CHAR_THRESHOLD;this._classesToPreserve=this.CLASSES_TO_PRESERVE.concat(options.classesToPreserve||[]);this._flags=this.FLAG_STRIP_UNLIKELYS|this.FLAG_WEIGHT_CLASSES|this.FLAG_CLEAN_CONDITIONALLY;var logEl;if(this._debug){logEl=function(e){var rv=e.nodeName+" ";if(e.nodeType==e.TEXT_NODE){return rv+'("'+e.textContent+'")';}
var classDesc=e.className&&("."+e.className.replace(/ /g,"."));var elDesc="";if(e.id)
elDesc="(#"+e.id+classDesc+")";else if(classDesc)
elDesc="("+classDesc+")";return rv+elDesc;};this.log=function(){if(typeof dump!=="undefined"){var msg=Array.prototype.map.call(arguments,function(x){return(x&&x.nodeName)?logEl(x):x;}).join(" ");dump("Reader: (Readability) "+msg+"\n");}else if(typeof console!=="undefined"){var args=["Reader: (Readability) "].concat(arguments);console.log.apply(console,args);}};}else{this.log=function(){};}}
Readability.prototype={FLAG_STRIP_UNLIKELYS:0x1,FLAG_WEIGHT_CLASSES:0x2,FLAG_CLEAN_CONDITIONALLY:0x4,DEFAULT_MAX_ELEMS_TO_PARSE:0,DEFAULT_N_TOP_CANDIDATES:5,DEFAULT_TAGS_TO_SCORE:"section,h2,h3,h4,h5,h6,p,td,pre".toUpperCase().split(","),DEFAULT_CHAR_THRESHOLD:500,REGEXPS:{unlikelyCandidates:/banner|breadcrumbs|combx|comment|community|cover-wrap|disqus|extra|foot|header|legends|menu|related|remark|replies|rss|shoutbox|sidebar|skyscraper|social|sponsor|supplemental|ad-break|agegate|pagination|pager|popup|yom-remote/i,okMaybeItsACandidate:/and|article|body|column|main|shadow/i,positive:/article|body|wrapper|content|entry|hentry|h-entry|main|page|pagination|post|text|blog|story/i,negative:/hidden|^hid$| hid$| hid |^hid |banner|combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|outbrain|promo|related|scroll|share|shoutbox|sidebar|skyscraper|sponsor|shopping|tags|tool|widget/i,extraneous:/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|utility/i,byline:/byline|author|dateline|writtenby|p-author/i,replaceFonts:/<(\/?)font[^>]*>/gi,normalize:/\s{2,}/g,videos:/\/\/(www\.)?(dailymotion|youtube|youtube-nocookie|player\.vimeo)\.com/i,nextLink:/(next|weiter|continue|>([^\|]|$)|»([^\|]|$))/i,prevLink:/(prev|earl|old|new|<|«)/i,whitespace:/^\s*$/,hasContent:/\S$/,},DIV_TO_P_ELEMS:["A","BLOCKQUOTE","DL","DIV","IMG","OL","P","PRE","TABLE","UL","SELECT"],ALTER_TO_DIV_EXCEPTIONS:["DIV","ARTICLE","SECTION","P"],PRESENTATIONAL_ATTRIBUTES:["align","background","bgcolor","border","cellpadding","cellspacing","frame","hspace","rules","style","valign","vspace"],DEPRECATED_SIZE_ATTRIBUTE_ELEMS:["TABLE","TH","TD","HR","PRE"],CLASSES_TO_PRESERVE:["readability-styled","page"],_postProcessContent:function(articleContent){this._fixRelativeUris(articleContent);this._cleanClasses(articleContent);},_removeNodes:function(nodeList,filterFn){for(var i=nodeList.length-1;i>=0;i--){var node=nodeList[i];var parentNode=node.parentNode;if(parentNode){if(!filterFn||filterFn.call(this,node,i,nodeList)){parentNode.removeChild(node);}}}},_replaceNodeTags:function(nodeList,newTagName){for(var i=nodeList.length-1;i>=0;i--){var node=nodeList[i];this._setNodeTag(node,newTagName);}},_forEachNode:function(nodeList,fn){Array.prototype.forEach.call(nodeList,fn,this);},_someNode:function(nodeList,fn){return Array.prototype.some.call(nodeList,fn,this);},_concatNodeLists:function(){var slice=Array.prototype.slice;var args=slice.call(arguments);var nodeLists=args.map(function(list){return slice.call(list);});return Array.prototype.concat.apply([],nodeLists);},_getAllNodesWithTag:function(node,tagNames){if(node.querySelectorAll){return node.querySelectorAll(tagNames.join(','));}
return[].concat.apply([],tagNames.map(function(tag){var collection=node.getElementsByTagName(tag);return Array.isArray(collection)?collection:Array.from(collection);}));},_cleanClasses:function(node){var classesToPreserve=this._classesToPreserve;var className=(node.getAttribute("class")||"").split(/\s+/).filter(function(cls){return classesToPreserve.indexOf(cls)!=-1;}).join(" ");if(className){node.setAttribute("class",className);}else{node.removeAttribute("class");}
for(node=node.firstElementChild;node;node=node.nextElementSibling){this._cleanClasses(node);}},_fixRelativeUris:function(articleContent){var baseURI=this._doc.baseURI;var documentURI=this._doc.documentURI;function toAbsoluteURI(uri){if(baseURI==documentURI&&uri.charAt(0)=="#"){return uri;}
try{return new URL(uri,baseURI).href;}catch(ex){}
return uri;}
var links=articleContent.getElementsByTagName("a");this._forEachNode(links,function(link){var href=link.getAttribute("href");if(href){if(href.indexOf("javascript:")===0){var text=this._doc.createTextNode(link.textContent);link.parentNode.replaceChild(text,link);}else{link.setAttribute("href",toAbsoluteURI(href));}}});var imgs=articleContent.getElementsByTagName("img");this._forEachNode(imgs,function(img){var src=img.getAttribute("src");if(src){img.setAttribute("src",toAbsoluteURI(src));}});},_getArticleTitle:function(){var doc=this._doc;var curTitle="";var origTitle="";try{curTitle=origTitle=doc.title;if(typeof curTitle!=="string")
curTitle=origTitle=this._getInnerText(doc.getElementsByTagName('title')[0]);}catch(e){}
var titleHadHierarchicalSeparators=false;function wordCount(str){return str.split(/\s+/).length;}
if((/ [\|\-\\\/>»] /).test(curTitle)){titleHadHierarchicalSeparators=/ [\\\/>»] /.test(curTitle);curTitle=origTitle.replace(/(.*)[\|\-\\\/>»] .*/gi,'$1');if(wordCount(curTitle)<3)
curTitle=origTitle.replace(/[^\|\-\\\/>»]*[\|\-\\\/>»](.*)/gi,'$1');}else if(curTitle.indexOf(': ')!==-1){var headings=this._concatNodeLists(doc.getElementsByTagName('h1'),doc.getElementsByTagName('h2'));var match=this._someNode(headings,function(heading){return heading.textContent===curTitle;});if(!match){curTitle=origTitle.substring(origTitle.lastIndexOf(':')+1);if(wordCount(curTitle)<3){curTitle=origTitle.substring(origTitle.indexOf(':')+1);}else if(wordCount(origTitle.substr(0,origTitle.indexOf(':')))>5){curTitle=origTitle;}}}else if(curTitle.length>150||curTitle.length<15){var hOnes=doc.getElementsByTagName('h1');if(hOnes.length===1)
curTitle=this._getInnerText(hOnes[0]);}
curTitle=curTitle.trim();var curTitleWordCount=wordCount(curTitle);if(curTitleWordCount<=4&&(!titleHadHierarchicalSeparators||curTitleWordCount!=wordCount(origTitle.replace(/[\|\-\\\/>»]+/g,""))-1)){curTitle=origTitle;}
return curTitle;},_prepDocument:function(){var doc=this._doc;this._removeNodes(doc.getElementsByTagName("style"));if(doc.body){this._replaceBrs(doc.body);}
this._replaceNodeTags(doc.getElementsByTagName("font"),"SPAN");},_nextElement:function(node){var next=node;while(next&&(next.nodeType!=Node.ELEMENT_NODE)&&this.REGEXPS.whitespace.test(next.textContent)){next=next.nextSibling;}
return next;},_replaceBrs:function(elem){this._forEachNode(this._getAllNodesWithTag(elem,["br"]),function(br){var next=br.nextSibling;var replaced=false;while((next=this._nextElement(next))&&(next.tagName=="BR")){replaced=true;var brSibling=next.nextSibling;next.parentNode.removeChild(next);next=brSibling;}
if(replaced){var p=this._doc.createElement("p");br.parentNode.replaceChild(p,br);next=p.nextSibling;while(next){if(next.tagName=="BR"){var nextElem=this._nextElement(next);if(nextElem&&nextElem.tagName=="BR")
break;}
var sibling=next.nextSibling;p.appendChild(next);next=sibling;}}});},_setNodeTag:function(node,tag){this.log("_setNodeTag",node,tag);if(node.__JSDOMParser__){node.localName=tag.toLowerCase();node.tagName=tag.toUpperCase();return node;}
var replacement=node.ownerDocument.createElement(tag);while(node.firstChild){replacement.appendChild(node.firstChild);}
node.parentNode.replaceChild(replacement,node);if(node.readability)
replacement.readability=node.readability;for(var i=0;i<node.attributes.length;i++){replacement.setAttribute(node.attributes[i].name,node.attributes[i].value);}
return replacement;},_prepArticle:function(articleContent){this._cleanStyles(articleContent);this._markDataTables(articleContent);this._cleanConditionally(articleContent,"form");this._cleanConditionally(articleContent,"fieldset");this._clean(articleContent,"object");this._clean(articleContent,"embed");this._clean(articleContent,"h1");this._clean(articleContent,"footer");this._clean(articleContent,"link");this._forEachNode(articleContent.children,function(topCandidate){this._cleanMatchedNodes(topCandidate,/share/);});var h2=articleContent.getElementsByTagName('h2');if(h2.length===1){var lengthSimilarRate=(h2[0].textContent.length-this._articleTitle.length)/this._articleTitle.length;if(Math.abs(lengthSimilarRate)<0.5){var titlesMatch=false;if(lengthSimilarRate>0){titlesMatch=h2[0].textContent.includes(this._articleTitle);}else{titlesMatch=this._articleTitle.includes(h2[0].textContent);}
if(titlesMatch){this._clean(articleContent,"h2");}}}
this._clean(articleContent,"iframe");this._clean(articleContent,"input");this._clean(articleContent,"textarea");this._clean(articleContent,"select");this._clean(articleContent,"button");this._clean(articleContent,"audima-div");this._clean(articleContent,"audima-span");this._clean(articleContent,"audima-p");this._cleanHeaders(articleContent);this._cleanConditionally(articleContent,"table");this._cleanConditionally(articleContent,"ul");this._cleanConditionally(articleContent,"div");this._removeNodes(articleContent.getElementsByTagName('p'),function(paragraph){var imgCount=paragraph.getElementsByTagName('img').length;var embedCount=paragraph.getElementsByTagName('embed').length;var objectCount=paragraph.getElementsByTagName('object').length;var audimaDiv=paragraph.getElementsByTagName('audima-div').length;var audimaSpan=paragraph.getElementsByTagName('audima-span"').length;var audimaP=paragraph.getElementsByTagName('audima-p"').length;var iframeCount=paragraph.getElementsByTagName('iframe').length;var totalCount=imgCount+embedCount+objectCount+iframeCount+audimaDiv+audimaSpan+audimaP;return totalCount===0&&!this._getInnerText(paragraph,false);});this._forEachNode(this._getAllNodesWithTag(articleContent,["br"]),function(br){var next=this._nextElement(br.nextSibling);if(next&&next.tagName=="P")
br.parentNode.removeChild(br);});},_initializeNode:function(node){node.readability={"contentScore":0};switch(node.tagName){case 'DIV':node.readability.contentScore+=5;break;case 'PRE':case 'TD':case 'BLOCKQUOTE':node.readability.contentScore+=3;break;case 'ADDRESS':case 'OL':case 'UL':case 'DL':case 'DD':case 'DT':case 'LI':case 'FORM':node.readability.contentScore-=3;break;case 'H1':case 'H2':case 'H3':case 'H4':case 'H5':case 'H6':case 'TH':node.readability.contentScore-=5;break;}
node.readability.contentScore+=this._getClassWeight(node);},_removeAndGetNext:function(node){var nextNode=this._getNextNode(node,true);node.parentNode.removeChild(node);return nextNode;},_getNextNode:function(node,ignoreSelfAndKids){if(!ignoreSelfAndKids&&node.firstElementChild){return node.firstElementChild;}
if(node.nextElementSibling){return node.nextElementSibling;}
do{node=node.parentNode;}while(node&&!node.nextElementSibling);return node&&node.nextElementSibling;},_getNextNodeNoElementProperties:function(node,ignoreSelfAndKids){function nextSiblingEl(n){do{n=n.nextSibling;}while(n&&n.nodeType!==n.ELEMENT_NODE);return n;}
if(!ignoreSelfAndKids&&node.children[0]){return node.children[0];}
var next=nextSiblingEl(node);if(next){return next;}
do{node=node.parentNode;if(node)
next=nextSiblingEl(node);}while(node&&!next);return node&&next;},_checkByline:function(node,matchString){if(this._articleByline){return false;}
if(node.getAttribute!==undefined){var rel=node.getAttribute("rel");}
if((rel==="author"||this.REGEXPS.byline.test(matchString))&&this._isValidByline(node.textContent)){this._articleByline=node.textContent.trim();return true;}
return false;},_getNodeAncestors:function(node,maxDepth){maxDepth=maxDepth||0;var i=0,ancestors=[];while(node.parentNode){ancestors.push(node.parentNode);if(maxDepth&&++i===maxDepth)
break;node=node.parentNode;}
return ancestors;},_grabArticle:function(page){this.log("**** grabArticle ****");var doc=this._doc;var isPaging=(page!==null?true:false);page=page?page:this._doc.body;if(!page){this.log("No body found in document. Abort.");return null;}
var pageCacheHtml=page.innerHTML;while(true){var stripUnlikelyCandidates=this._flagIsActive(this.FLAG_STRIP_UNLIKELYS);var elementsToScore=[];var node=this._doc.documentElement;while(node){var matchString=node.className+" "+node.id;if(this._checkByline(node,matchString)){node=this._removeAndGetNext(node);continue;}
if(stripUnlikelyCandidates){if(this.REGEXPS.unlikelyCandidates.test(matchString)&&!this.REGEXPS.okMaybeItsACandidate.test(matchString)&&node.tagName!=="BODY"&&node.tagName!=="A"){this.log("Removing unlikely candidate - "+matchString);node=this._removeAndGetNext(node);continue;}}
if((window.location.hostname==="tucnews.com.br"&&node.id==="about_the_author")||(window.location.hostname==="tucnews.com.br"&&node.tagName==='H5')||(window.location.hostname==="tucnews.com.br"&&node.className==='post_related')||(window.location.hostname==="tucnews.com.br"&&node.className==='post_more')||(window.location.hostname==="tucnews.com.br"&&node.className==='comment-respond')){node=this._removeAndGetNext(node);continue;}
if((window.location.hostname==="oglobo.globo.com"||window.location.hostname==="m.oglobo.globo.com")&&node.className==='article__picture-caption'){node=this._removeAndGetNext(node);continue;}
if((window.location.hostname==="blogs.oglobo.globo.com")&&(node.className==='meta'||node.tagName==='H2'||node.className==='tag'||node.className==='leftBar'||node.className==='sidebar')){node=this._removeAndGetNext(node);continue;}
if(node.id==="galeria_embed"||(node.className==='instagram-media')){node=this._removeAndGetNext(node);continue;}
if((node.className=='hidden-title'&&node.tagName==='SPAN')||(node.className=='hidden-url'&&node.tagName==='SPAN')){node=this._removeAndGetNext(node);continue;}
if((node.tagName==="DIV"||node.tagName==="SECTION"||node.tagName==="HEADER"||node.tagName==="H1"||node.tagName==="H2"||node.tagName==="H3"||node.tagName==="H4"||node.tagName==="H5"||node.tagName==="H6"||node.tagName==="audima-div"||node.tagName==="audima-span"||node.tagName==="audima-p")&&this._isElementWithoutContent(node)){node=this._removeAndGetNext(node);continue;}
if(this.DEFAULT_TAGS_TO_SCORE.indexOf(node.tagName)!==-1){elementsToScore.push(node);}
if(node.tagName==="DIV"){if(this._hasSinglePInsideElement(node)){var newNode=node.children[0];node.parentNode.replaceChild(newNode,node);node=newNode;elementsToScore.push(node);}else if(!this._hasChildBlockElement(node)){node=this._setNodeTag(node,"P");elementsToScore.push(node);}else{this._forEachNode(node.childNodes,function(childNode){if(window.location.hostname==="www.facha.edu.br"&&childNode.tagName==="DIV"){var p=doc.createElement('p');p.textContent=childNode.textContent;p.style.display='inline';p.className='readability-styled';node.replaceChild(p,childNode);}
if((childNode.tagName==="SPAN"||childNode.tagName==="P")&&childNode.textContent){var p=doc.createElement('p');p.textContent=childNode.textContent;p.style.display='inline';p.className='readability-styled';node.replaceChild(p,childNode);}
if(childNode.nodeType===Node.TEXT_NODE&&childNode.textContent.trim().length>0){var p=doc.createElement('p');p.textContent=childNode.textContent;p.style.display='inline';p.className='readability-styled';node.replaceChild(p,childNode);}});}}
node=this._getNextNode(node);}
var candidates=[];this._forEachNode(elementsToScore,function(elementToScore){if(!elementToScore.parentNode||typeof(elementToScore.parentNode.tagName)==='undefined')
return;var innerText=this._getInnerText(elementToScore);if(innerText.length<25)
return;var ancestors=this._getNodeAncestors(elementToScore,3);if(ancestors.length===0)
return;var contentScore=0;contentScore+=1;contentScore+=innerText.split(',').length;contentScore+=Math.min(Math.floor(innerText.length/100),3);this._forEachNode(ancestors,function(ancestor,level){if(!ancestor.tagName)
return;if(typeof(ancestor.readability)==='undefined'){this._initializeNode(ancestor);candidates.push(ancestor);}
if(level===0)
var scoreDivider=1;else if(level===1)
scoreDivider=2;else
scoreDivider=level*3;ancestor.readability.contentScore+=contentScore/scoreDivider;});});var topCandidates=[];for(var c=0,cl=candidates.length;c<cl;c+=1){var candidate=candidates[c];var candidateScore=candidate.readability.contentScore*(1-this._getLinkDensity(candidate));candidate.readability.contentScore=candidateScore;this.log('Candidate:',candidate,"with score "+candidateScore);for(var t=0;t<this._nbTopCandidates;t++){var aTopCandidate=topCandidates[t];if(!aTopCandidate||candidateScore>aTopCandidate.readability.contentScore){topCandidates.splice(t,0,candidate);if(topCandidates.length>this._nbTopCandidates)
topCandidates.pop();break;}}}
var topCandidate=topCandidates[0]||null;var neededToCreateTopCandidate=false;var parentOfTopCandidate;if(topCandidate===null||topCandidate.tagName==="BODY"){topCandidate=doc.createElement("DIV");neededToCreateTopCandidate=true;var kids=page.childNodes;while(kids.length){this.log("Moving child out:",kids[0]);topCandidate.appendChild(kids[0]);}
page.appendChild(topCandidate);this._initializeNode(topCandidate);}else if(topCandidate){var alternativeCandidateAncestors=[];for(var i=1;i<topCandidates.length;i++){if(topCandidates[i].readability.contentScore/topCandidate.readability.contentScore>=0.75){alternativeCandidateAncestors.push(this._getNodeAncestors(topCandidates[i]));}}
var MINIMUM_TOPCANDIDATES=3;if(alternativeCandidateAncestors.length>=MINIMUM_TOPCANDIDATES){parentOfTopCandidate=topCandidate.parentNode;while(parentOfTopCandidate.tagName!=="BODY"){var listsContainingThisAncestor=0;for(var ancestorIndex=0;ancestorIndex<alternativeCandidateAncestors.length&&listsContainingThisAncestor<MINIMUM_TOPCANDIDATES;ancestorIndex++){listsContainingThisAncestor+=Number(alternativeCandidateAncestors[ancestorIndex].includes(parentOfTopCandidate));}
if(listsContainingThisAncestor>=MINIMUM_TOPCANDIDATES){topCandidate=parentOfTopCandidate;break;}
parentOfTopCandidate=parentOfTopCandidate.parentNode;}}
if(!topCandidate.readability){this._initializeNode(topCandidate);}
parentOfTopCandidate=topCandidate.parentNode;var lastScore=topCandidate.readability.contentScore;var scoreThreshold=lastScore/3;while(parentOfTopCandidate.tagName!=="BODY"){if(!parentOfTopCandidate.readability){parentOfTopCandidate=parentOfTopCandidate.parentNode;continue;}
var parentScore=parentOfTopCandidate.readability.contentScore;if(parentScore<scoreThreshold)
break;if(parentScore>lastScore){topCandidate=parentOfTopCandidate;break;}
lastScore=parentOfTopCandidate.readability.contentScore;parentOfTopCandidate=parentOfTopCandidate.parentNode;}
parentOfTopCandidate=topCandidate.parentNode;while(parentOfTopCandidate.tagName!="BODY"&&parentOfTopCandidate.children.length==1){topCandidate=parentOfTopCandidate;parentOfTopCandidate=topCandidate.parentNode;}
if(!topCandidate.readability){this._initializeNode(topCandidate);}}
var articleContent=doc.createElement("DIV");if(isPaging)
articleContent.id="readability-content";var siblingScoreThreshold=Math.max(10,topCandidate.readability.contentScore*0.2);parentOfTopCandidate=topCandidate.parentNode;var siblings=parentOfTopCandidate.children;for(var s=0,sl=siblings.length;s<sl;s++){var sibling=siblings[s];var append=false;this.log("Looking at sibling node:",sibling,sibling.readability?("with score "+sibling.readability.contentScore):'');this.log("Sibling has score",sibling.readability?sibling.readability.contentScore:'Unknown');if(sibling===topCandidate){append=true;}else{var contentBonus=0;if(sibling.className===topCandidate.className&&topCandidate.className!=="")
contentBonus+=topCandidate.readability.contentScore*0.2;if(sibling.readability&&((sibling.readability.contentScore+contentBonus)>=siblingScoreThreshold)){append=true;}else if(sibling.nodeName==="P"){var linkDensity=this._getLinkDensity(sibling);var nodeContent=this._getInnerText(sibling);var nodeLength=nodeContent.length;if(nodeLength>80&&linkDensity<0.25){append=true;}else if(nodeLength<80&&nodeLength>0&&linkDensity===0&&nodeContent.search(/\.( |$)/)!==-1){append=true;}}}
if(append){this.log("Appending node:",sibling);if(this.ALTER_TO_DIV_EXCEPTIONS.indexOf(sibling.nodeName)===-1){this.log("Altering sibling:",sibling,'to div.');sibling=this._setNodeTag(sibling,"DIV");}
articleContent.appendChild(sibling);s-=1;sl-=1;}}
if(this._debug)
this.log("Article content pre-prep: "+articleContent.innerHTML);this._prepArticle(articleContent);if(this._debug)
this.log("Article content post-prep: "+articleContent.innerHTML);if(neededToCreateTopCandidate){topCandidate.id="readability-page-2";topCandidate.className="page";}else{}
if(this._debug)
this.log("Article content after paging: "+articleContent.innerHTML);var parseSuccessful=true;var textLength=this._getInnerText(articleContent,true).length;if(textLength<this._charThreshold){parseSuccessful=false;page.innerHTML=pageCacheHtml;if(this._flagIsActive(this.FLAG_STRIP_UNLIKELYS)){this._removeFlag(this.FLAG_STRIP_UNLIKELYS);this._attempts.push({articleContent:articleContent,textLength:textLength});}else if(this._flagIsActive(this.FLAG_WEIGHT_CLASSES)){this._removeFlag(this.FLAG_WEIGHT_CLASSES);this._attempts.push({articleContent:articleContent,textLength:textLength});}else if(this._flagIsActive(this.FLAG_CLEAN_CONDITIONALLY)){this._removeFlag(this.FLAG_CLEAN_CONDITIONALLY);this._attempts.push({articleContent:articleContent,textLength:textLength});}else{this._attempts.push({articleContent:articleContent,textLength:textLength});this._attempts.sort(function(a,b){return a.textLength<b.textLength;});if(!this._attempts[0].textLength){return null;}
articleContent=this._attempts[0].articleContent;parseSuccessful=true;}}
if(parseSuccessful){var ancestors=[parentOfTopCandidate,topCandidate].concat(this._getNodeAncestors(parentOfTopCandidate));this._someNode(ancestors,function(ancestor){if(!ancestor.tagName)
return false;var articleDir=ancestor.getAttribute("dir");if(articleDir){this._articleDir=articleDir;return true;}
return false;});return articleContent;}}},_isValidByline:function(byline){if(typeof byline=='string'||byline instanceof String){byline=byline.trim();return(byline.length>0)&&(byline.length<100);}
return false;},_getArticleMetadata:function(){var metadata={};var values={};var metaElements=this._doc.getElementsByTagName("meta");var namePattern=/^\s*((twitter)\s*:\s*)?(description|title)\s*$/gi;var propertyPattern=/^\s*og\s*:\s*(description|title)\s*$/gi;this._forEachNode(metaElements,function(element){var elementName=element.getAttribute("name");var elementProperty=element.getAttribute("property");if([elementName,elementProperty].indexOf("author")!==-1){metadata.byline=element.getAttribute("content");return;}
var name=null;if(namePattern.test(elementName)){name=elementName;}else if(propertyPattern.test(elementProperty)){name=elementProperty;}
if(name){var content=element.getAttribute("content");if(content){name=name.toLowerCase().replace(/\s/g,'');values[name]=content.trim();}}});if("description"in values){metadata.excerpt=values["description"];}else if("og:description"in values){metadata.excerpt=values["og:description"];}else if("twitter:description"in values){metadata.excerpt=values["twitter:description"];}
metadata.title=this._getArticleTitle();if(!metadata.title){if("og:title"in values){metadata.title=values["og:title"];}else if("twitter:title"in values){metadata.title=values["twitter:title"];}}
return metadata;},_removeScripts:function(doc){this._removeNodes(doc.getElementsByTagName('script'),function(scriptNode){scriptNode.nodeValue="";scriptNode.removeAttribute('src');return true;});this._removeNodes(doc.getElementsByTagName('noscript'));},_hasSinglePInsideElement:function(element){if(element.children.length!=1||element.children[0].tagName!=="P"){return false;}
return!this._someNode(element.childNodes,function(node){return node.nodeType===Node.TEXT_NODE&&this.REGEXPS.hasContent.test(node.textContent);});},_isElementWithoutContent:function(node){return node.nodeType===Node.ELEMENT_NODE&&node.textContent.trim().length==0&&(node.children.length==0||node.children.length==node.getElementsByTagName("br").length+node.getElementsByTagName("hr").length);},_hasChildBlockElement:function(element){return this._someNode(element.childNodes,function(node){return this.DIV_TO_P_ELEMS.indexOf(node.tagName)!==-1||this._hasChildBlockElement(node);});},_getInnerText:function(e,normalizeSpaces){normalizeSpaces=(typeof normalizeSpaces==='undefined')?true:normalizeSpaces;var textContent=e.textContent.trim();if(normalizeSpaces){return textContent.replace(this.REGEXPS.normalize," ");}
return textContent;},_getCharCount:function(e,s){s=s||",";return this._getInnerText(e).split(s).length-1;},_cleanStyles:function(e){if(!e||e.tagName.toLowerCase()==='svg')
return;if(e.className!=='readability-styled'){for(var i=0;i<this.PRESENTATIONAL_ATTRIBUTES.length;i++){e.removeAttribute(this.PRESENTATIONAL_ATTRIBUTES[i]);}
if(this.DEPRECATED_SIZE_ATTRIBUTE_ELEMS.indexOf(e.tagName)!==-1){e.removeAttribute('width');e.removeAttribute('height');}}
var cur=e.firstElementChild;while(cur!==null){this._cleanStyles(cur);cur=cur.nextElementSibling;}},_getLinkDensity:function(element){var textLength=this._getInnerText(element).length;if(textLength===0)
return 0;var linkLength=0;this._forEachNode(element.getElementsByTagName("a"),function(linkNode){linkLength+=this._getInnerText(linkNode).length;});return linkLength/textLength;},_getClassWeight:function(e){if(!this._flagIsActive(this.FLAG_WEIGHT_CLASSES))
return 0;var weight=0;if(typeof(e.className)==='string'&&e.className!==''){if(this.REGEXPS.negative.test(e.className))
weight-=25;if(this.REGEXPS.positive.test(e.className))
weight+=25;}
if(typeof(e.id)==='string'&&e.id!==''){if(this.REGEXPS.negative.test(e.id))
weight-=25;if(this.REGEXPS.positive.test(e.id))
weight+=25;}
return weight;},_clean:function(e,tag){var isEmbed=["object","embed","iframe","audima-div","audima-span","audima-p"].indexOf(tag)!==-1;this._removeNodes(e.getElementsByTagName(tag),function(element){if(isEmbed){var attributeValues=[].map.call(element.attributes,function(attr){return attr.value;}).join("|");if(this.REGEXPS.videos.test(attributeValues))
return false;if(this.REGEXPS.videos.test(element.innerHTML))
return false;}
return true;});},_hasAncestorTag:function(node,tagName,maxDepth,filterFn){maxDepth=maxDepth||3;tagName=tagName.toUpperCase();var depth=0;while(node.parentNode){if(maxDepth>0&&depth>maxDepth)
return false;if(node.parentNode.tagName===tagName&&(!filterFn||filterFn(node.parentNode)))
return true;node=node.parentNode;depth++;}
return false;},_getRowAndColumnCount:function(table){var rows=0;var columns=0;var trs=table.getElementsByTagName("tr");for(var i=0;i<trs.length;i++){var rowspan=trs[i].getAttribute("rowspan")||0;if(rowspan){rowspan=parseInt(rowspan,10);}
rows+=(rowspan||1);var columnsInThisRow=0;var cells=trs[i].getElementsByTagName("td");for(var j=0;j<cells.length;j++){var colspan=cells[j].getAttribute("colspan")||0;if(colspan){colspan=parseInt(colspan,10);}
columnsInThisRow+=(colspan||1);}
columns=Math.max(columns,columnsInThisRow);}
return{rows:rows,columns:columns};},_markDataTables:function(root){var tables=root.getElementsByTagName("table");for(var i=0;i<tables.length;i++){var table=tables[i];var role=table.getAttribute("role");if(role=="presentation"){table._readabilityDataTable=false;continue;}
var datatable=table.getAttribute("datatable");if(datatable=="0"){table._readabilityDataTable=false;continue;}
var summary=table.getAttribute("summary");if(summary){table._readabilityDataTable=true;continue;}
var caption=table.getElementsByTagName("caption")[0];if(caption&&caption.childNodes.length>0){table._readabilityDataTable=true;continue;}
var dataTableDescendants=["col","colgroup","tfoot","thead","th"];var descendantExists=function(tag){return!!table.getElementsByTagName(tag)[0];};if(dataTableDescendants.some(descendantExists)){this.log("Data table because found data-y descendant");table._readabilityDataTable=true;continue;}
if(table.getElementsByTagName("table")[0]){table._readabilityDataTable=false;continue;}
var sizeInfo=this._getRowAndColumnCount(table);if(sizeInfo.rows>=10||sizeInfo.columns>4){table._readabilityDataTable=true;continue;}
table._readabilityDataTable=sizeInfo.rows*sizeInfo.columns>10;}},_cleanConditionally:function(e,tag){if(!this._flagIsActive(this.FLAG_CLEAN_CONDITIONALLY))
return;var isList=tag==="ul"||tag==="ol";this._removeNodes(e.getElementsByTagName(tag),function(node){var isDataTable=function(t){return t._readabilityDataTable;};if(this._hasAncestorTag(node,"table",-1,isDataTable)){return false;}
var weight=this._getClassWeight(node);var contentScore=0;this.log("Cleaning Conditionally",node);if(weight+contentScore<0){return true;}
if(this._getCharCount(node,',')<10){var p=node.getElementsByTagName("p").length;var img=node.getElementsByTagName("img").length;var li=node.getElementsByTagName("li").length-100;var input=node.getElementsByTagName("input").length;var embedCount=0;var embeds=node.getElementsByTagName("embed");for(var ei=0,il=embeds.length;ei<il;ei+=1){if(!this.REGEXPS.videos.test(embeds[ei].src))
embedCount+=1;}
var linkDensity=this._getLinkDensity(node);var contentLength=this._getInnerText(node).length;var haveToRemove=(img>1&&p/img<0.5&&!this._hasAncestorTag(node,"figure"))||(!isList&&li>p)||(input>Math.floor(p/3))||(!isList&&contentLength<25&&(img===0||img>2)&&!this._hasAncestorTag(node,"figure"))||(!isList&&weight<25&&linkDensity>0.2)||(weight>=25&&linkDensity>0.5)||((embedCount===1&&contentLength<75)||embedCount>1);return haveToRemove;}
return false;});},_cleanMatchedNodes:function(e,regex){var endOfSearchMarkerNode=this._getNextNode(e,true);var next=this._getNextNode(e);while(next&&next!=endOfSearchMarkerNode){if(regex.test(next.className+" "+next.id)){next=this._removeAndGetNext(next);}else{next=this._getNextNode(next);}}},_cleanHeaders:function(e){for(var headerIndex=1;headerIndex<3;headerIndex+=1){this._removeNodes(e.getElementsByTagName('h'+headerIndex),function(header){return this._getClassWeight(header)<0;});}},_flagIsActive:function(flag){return(this._flags&flag)>0;},_removeFlag:function(flag){this._flags=this._flags&~flag;},isProbablyReaderable:function(helperIsVisible){var nodes=this._getAllNodesWithTag(this._doc,["p","pre"]);var brNodes=this._getAllNodesWithTag(this._doc,["div > br"]);if(brNodes.length){var set=new Set();[].forEach.call(brNodes,function(node){set.add(node.parentNode);});nodes=[].concat.apply(Array.from(set),nodes);}
var score=0;return this._someNode(nodes,function(node){if(helperIsVisible&&!helperIsVisible(node))
return false;var matchString=node.className+" "+node.id;if(this.REGEXPS.unlikelyCandidates.test(matchString)&&!this.REGEXPS.okMaybeItsACandidate.test(matchString)){return false;}
if(node.matches&&node.matches("li p")){return false;}
var textContentLength=node.textContent.trim().length;if(textContentLength<140){return false;}
score+=Math.sqrt(textContentLength-140);if(score>20){return true;}
return false;});},parse:function(){if(this._maxElemsToParse>0){var numTags=this._doc.getElementsByTagName("*").length;if(numTags>this._maxElemsToParse){throw new Error("Aborting parsing document; "+numTags+" elements found");}}
if(typeof this._doc.documentElement.firstElementChild==="undefined"){this._getNextNode=this._getNextNodeNoElementProperties;}
this._removeScripts(this._doc);this._prepDocument();var metadata=this._getArticleMetadata();this._articleTitle=metadata.title;var articleContent=this._grabArticle();if(!articleContent)
return null;this.log("Grabbed: "+articleContent.innerHTML);this._postProcessContent(articleContent);if(!metadata.excerpt){var paragraphs=articleContent.getElementsByTagName("p");if(paragraphs.length>0){metadata.excerpt=paragraphs[0].textContent.trim();}}
var textContent=articleContent.textContent;return{uri:this._uri,title:this._articleTitle,byline:metadata.byline||this._articleByline,dir:this._articleDir,content:articleContent.innerHTML,textContent:textContent,length:textContent.length,excerpt:metadata.excerpt,};}};if(typeof module==="object"){module.exports=Readability;}