//tealium universal tag - utag.1 ut4.0.201812181754, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.kvp_delim="=";u.divid="";u.slot="";u.height="";u.width="";u.collapseEmptyDivs="true";u.base_url="//www.googletagservices.com/tag/js/gpt.js";u.map={"ad_positions_list":"gptSlots","pageLevelTargeting":"pageLevelTargeting"};u.extend=[];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){u.setTargeting={};for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f]=="networkcode"||e[f]=="adunit"||e[f]=="slot"||e[f]=="gptSlots"||e[f]=="height"||e[f]=="width"||e[f]=="collapseEmptyDivs"||e[f]=="setTargeting_slot"||e[f]=="setTargeting"||e[f]=="pageLevelTargeting"){u[e[f]]=b[d]}else{u.setTargeting[e[f]]=b[d]}}}}
if(u.networkcode&&u.adunit){u.slot="/"+u.networkcode+"/"+u.adunit;}
u.gptSlots=u.gptSlots||((u.width===""&&u.height==="")?[[u.slot,null,u.divid]]:[[u.slot,[parseInt(u.width),parseInt(u.height)],u.divid]]);googletag.cmd.push(function(){for(f=0;f<u.gptSlots.length;f++){var slot;if(u.gptSlots[f][1]==null||u.gptSlots[f][1]=="OutOfPageSlot"){slot=googletag.defineOutOfPageSlot.apply(this,[u.gptSlots[f][0],u.gptSlots[f][2]]).addService(googletag.pubads());}else{slot=googletag.defineSlot.apply(this,u.gptSlots[f].slice(0,3)).addService(googletag.pubads());}
var data=u.gptSlots[f][3]||u.setTargeting_slot||{};for(d in data){slot.setTargeting(d+'',data[d])}
if(u.collapseEmptyDivs=="true"){slot.setCollapseEmptyDiv(true);}}
var pageData=u.pageLevelTargeting||{};try{pageData['ognCluster']=pageData['ognCluster'].concat(Krux.segments);}
catch(e){console.log("erro ao adicionar segmentos Krux ao ognCluster ",e);}
for(d in pageData){googletag.pubads().setTargeting(d+'',pageData[d])}
googletag.pubads().setTargeting("ksg",Krux.segments);googletag.pubads().setTargeting("kuid",Krux.user);googletag.pubads().setTargeting("bd_suser_code",utag_data.bd_suser_code);googletag.pubads().setTargeting("bd_suser_provider",utag_data.bd_suser_provider);googletag.pubads().addEventListener('slotRenderEnded',function(event){var div_id=event.slot.getSlotElementId();var publicidade_visivel=!event.isEmpty;var div=document.getElementById(div_id);if(div.closest('.block--advertising')!==null){if(publicidade_visivel){div.closest('.block--advertising').style.display='block';}else{div.closest('.block--advertising').style.display='none';}}
if(typeof dfp_callback!=="undefined"){dfp_callback()}});try{nvg13574.dfpnvg();}catch(e){}
googletag.enableServices();});googletag.cmd.push(function(){for(f in u.setTargeting){googletag.pubads().setTargeting(f,u.setTargeting[f]);}
for(f=0;f<u.gptSlots.length;f++){if(document.getElementById(u.gptSlots[f][2])){googletag.display(u.gptSlots[f][2]);}}});}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('1','globo.infoglobo.oglobo');}catch(e){}
