(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"1901241837330",f:(function(AMP,_){
var p,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=ba;
function ja(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Aa=b.prototype}
var t=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this),ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function u(){u=function(){};t.Symbol||(t.Symbol=la)}var la=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function ma(){u();var a=t.Symbol.iterator;a||(a=t.Symbol.iterator=t.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ka(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return na(this)}});ma=function(){}}function na(a){var b=0;return oa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function oa(a){ma();var b={next:a};b[t.Symbol.iterator]=function(){return this};return b}
function pa(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var qa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ra(a){var b=Object.create(null);if(!a)return b;for(var c;c=qa.exec(a);){var d=pa(c[1],c[1]),e=c[2]?pa(c[2],c[2]):"";b[d]=e}return b};var sa="";
function v(){var a,b=a||self;if(b.AMP_MODE)var c=b.AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=ra(c.location.originalHash||c.location.hash);d=d.spt;var g=ra(c.location.search);sa||(sa=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011901241837330");c=b.AMP_MODE={localDev:!1,development:!("1"!=f.development&&!c.AMP_DEV_MODE),examiner:"2"==f.development,filter:f.filter,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"1901241837330",rtvVersion:sa,
singlePassType:d}}return c};var ta=Object.prototype.toString;function Aa(a){return"[object Object]"===ta.call(a)};function Ba(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.log=self.log||{user:null,dev:null,userForEmbed:null};var Ca=self.log;function z(){if(!Ca.user)throw Error("failed to call initLogConstructor");return Ca.user}function A(){if(Ca.dev)return Ca.dev;throw Error("failed to call initLogConstructor");}
function B(a,b,c,d,e){return z().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var Da=Object.prototype.hasOwnProperty;function D(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function E(a){return a||{}}function Ea(a,b){if(Da.call(a,b))return a[b]}
function Fa(a,b){var c=10;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.t=b.t;a.s=b.s;a.d=b.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>c?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(Da.call(a.t,b)){var d=a.t[b];if(Aa(c)&&Aa(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}};function F(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var Ga,Ha="Webkit webkit Moz moz ms O o".split(" ");function Ia(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Ja(a){return AMP.BaseElement.apply(this,arguments)||this}ja(Ja,AMP.BaseElement);p=Ja.prototype;p.getLayoutPriority=function(){return 1};p.isAlwaysFixed=function(){return!0};p.isLayoutSupported=function(){return!0};p.renderOutsideViewport=function(){return!0};p.L=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function Ka(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function La(a,b){var c,d=a.ownerDocument.defaultView,e=d!=Ma(d);if(e){if(Na(d,b)){var f=H(d,b);if(f)return f}if(!c)return null}a=Oa(a);a=M(a);return Na(a,b)?H(a,b):null}function Pa(a,b){Ma(a);Na(a,"bind");Qa(a,a,"bind",function(){return b});H(a,"bind")}function N(a,b){a=Ma(a);return H(a,b)}function O(a,b){var c=Oa(a);c=M(c);return H(c,b)}function Ma(a){return a.__AMP_TOP||a}function Oa(a){return a.nodeType?N((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function M(a){a=Oa(a);return a.isSingleDoc()?a.win:a}function H(a,b){Na(a,b);var c=Ra(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Qa(a,b,c,d){var e=Ra(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=d,f.context=b,f.resolve&&H(a,c))}
function Sa(a,b){var c=Ta(a,b);if(c)return c;var d=new Ka,e=d,f=e.promise;e=e.resolve;Ra(a)[b]={obj:null,promise:f,resolve:e,context:null,ctor:null};return f}function Ta(a,b){var c=Ra(a)[b];if(c){if(c.promise)return c.promise;H(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Ra(a){var b=a.services;b||(b=a.services={});return b}function Na(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Ua(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function Va(a,b){Ua(a.documentElement,function(){return!!a.body},b)}function Wa(a){return new Promise(function(b){Va(a,b)})}function Xa(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}
function Ya(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function jb(a){var b=Ta(M(a),"bind");if(b)return b;var c=Oa(a);return c.whenBodyAvailable().then(function(){return kb(c.win,c.win.document.head)}).then(function(){var b=c.win;return b.ampExtendedElements&&b.ampExtendedElements["amp-bind"]?Sa(M(a),"bind"):null})}function lb(a){var b=La(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=Ma(b);return b!==c?mb(b):jb(a)}
function kb(a,b){if(b){var c=[];b=b.querySelectorAll("script[custom-element]");for(var d=0;d<b.length;d++)c.push(b[d].getAttribute("custom-element"))}else c=[];if(!c.includes("amp-bind"))return Promise.resolve();var e=N(a,"extensions");return e.waitForExtension(a,"amp-bind")}function mb(a){return Wa(a.document).then(function(){return kb(a,a.document.head)}).then(function(){return a.ampExtendedElements&&a.ampExtendedElements["amp-bind"]?Sa(a,"bind"):null})};function nb(){var a=100;this.ka=a;this.P=this.V=0;this.K=Object.create(null)}nb.prototype.has=function(a){return!!this.K[a]};nb.prototype.get=function(a){var b=this.K[a];if(b)return b.access=++this.P,b.payload};nb.prototype.put=function(a,b){this.has(a)||this.V++;this.K[a]={payload:b,access:this.P};if(!(this.V<=this.ka)){A().warn("lru-cache","Trimming LRU cache");a=this.K;var c=this.P+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.V--)}};var P=self.AMP_CONFIG||{},ob={thirdParty:P.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:P.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof P.thirdPartyFrameRegex?new RegExp(P.thirdPartyFrameRegex):P.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:P.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof P.cdnProxyRegex?new RegExp(P.cdnProxyRegex):P.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:P.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:P.localDev||!1};var pb=E({c:!0,v:!0,a:!0,ad:!0}),qb,rb,sb=/[?&]amp_js[^&]*/,tb=/[?&]amp_gsa[^&]*/,ub=/[?&]amp_r[^&]*/,vb=/[?&]amp_kit[^&]*/,wb=/[?&]usqp[^&]*/;
function Q(a){var b;qb||(qb=self.document.createElement("a"),rb=self.UrlCache||(self.UrlCache=new nb));var c=b?null:rb,d=qb;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}
function xb(a,b){var c=void 0===c?"source":c;B(null!=a,"%s %s must be available",b,c);var d=a;a=d;"string"==typeof a&&(a=Q(a));var e;(e="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,e=a.length-10,e=0<=e&&a.indexOf(".localhost",e)==e);B(e||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function yb(a){"string"==typeof a&&(a=Q(a));return ob.cdnProxyRegex.test(a.origin)}
function zb(a){"string"==typeof a&&(a=Q(a));if(!yb(a))return a.href;var b=a.pathname.split("/");B(pb[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);B(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");var e;e=(e=a.search)&&"?"!=e?(e=e.replace(sb,"").replace(tb,"").replace(ub,"").replace(vb,"").replace(wb,"").replace(/^[?&]/,""))?"?"+e:"":"";return b+e+(a.hash||"")}
function Ab(a,b){"string"==typeof b&&(b=Q(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=Q(d));c=c.replace(/\\/g,"/");var e=Q(c);c=F(c.toLowerCase(),e.protocol)?e.href:F(c,"//")?d.protocol+c:F(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Bb(a){var b=Q(a),c=ra(b.search);B(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Cb(a,b){if("."==b)return a;var c=b.split(".");for(b=0;b<c.length;b++){var d=c[b];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function Db(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}}
function Eb(a,b){var c=10;c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var f=Object.keys(b),g=Object.keys(c);if(f.length!==g.length)return!1;for(e=
0;e<f.length;e++){var h=f[e];a.push({a:b[h],b:c[h],depth:d-1})}continue}}if(b!==c)return!1}return!0};function Fb(a,b,c,d){var e=void 0;e=void 0===e?".":e;c=void 0===c?0:c;d=void 0===d?!1:d;xb(b.getAttribute("src"),b);var f=N(a.win,"batched-xhr");return Gb(b,c,d).then(function(a){return f.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");return Cb(a,e||".")})}
function Gb(a,b,c){var d=a.getAttribute("src"),e=La(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectUnwhitelistedVarsSync(a);if(0<f.length)throw z().createError("URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. "+('Please add data-amp-replace="'+f.join(" ")+'" to the ')+("<"+a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")?h.credentials=a.getAttribute("credentials"):
h.requireAmpResponseSourceOrigin=!1;c&&(h.cache="reload");return{xhrUrl:d,fetchOpt:h}})};function Hb(a){return AMP.BaseElement.apply(this,arguments)||this}ja(Hb,AMP.BaseElement);p=Hb.prototype;p.getLayoutPriority=function(){return 1};p.isAlwaysFixed=function(){return!0};p.isLayoutSupported=function(){return!0};p.buildCallback=function(){var a=this;Ia(this.element);this.element.setAttribute("aria-hidden","true");var b=O(this.getAmpDoc(),"viewer");b.whenFirstVisible().then(function(){return a.U()})};
p.mutatedAttributesCallback=function(a){if(O(this.getAmpDoc(),"viewer").hasBeenVisible())void 0!==a.src&&Ib(this,!1);else{var b=this.L();A().error(b,"Viewer must be visible before mutation.")}};p.renderOutsideViewport=function(){return!0};
p.U=function(){var a=this,b=this.element;b.hasAttribute("overridable")&&lb(b).then(function(a){a.makeStateKeyOverridable(b.getAttribute("id"))});0<b.children.length&&Jb(this);this.element.hasAttribute("src")&&Ib(this,!0);this.registerAction("refresh",function(){Ib(a,!1,!0)},100)};
function Jb(a){var b=a.L(),c=a.element.children;if(1!=c.length)a.user().error(b,"Should contain exactly one <script> child.");else{var d=c[0];Ya(d)?(c=Db(d.textContent,function(c){a.user().error(b,"Failed to parse state. Is it valid JSON?",c)}),Kb(a,c,!0)):a.user().error(b,'State should be in a <script> tag with type="application/json".')}}function Lb(a,b,c,d){var e=b.getAttribute("src"),f=1;if(c||Q(zb(e)).origin==Q(zb(a.win.location)).origin)f=2;return Fb(a,b,f,d)}
function Ib(a,b,c){var d=a.getAmpDoc();Lb(d,a.element,b,c).then(function(c){Kb(a,c,b)})}function Kb(a,b,c){if(void 0!==b&&null!==b){var d=B(a.element.id,"<amp-state> must have an id."),e=D();e[d]=b;lb(a.element).then(function(a){a.setState(e,c,!c)})}}p.L=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var Mb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function Nb(a){for(var b=[],c;c=Mb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new Ob(b)}
function Ob(a){B(0<a.length,"Srcset must have at least one source");this.I=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}B(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?Pb:Qb);this.ha=b}
Ob.prototype.select=function(a,b){if(this.ha){b*=a;a=this.I;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}}else for(a=this.I,c=0,d=Infinity,e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c;return this.I[b].url};Ob.prototype.getUrls=function(){return this.I.map(function(a){return a.url})};
Ob.prototype.stringify=function(a){for(var b=[],c=this.I,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.ha?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function Pb(a,b){B(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Qb(a,b){B(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Rb={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Sb={width:null,height:null},ac={"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,
"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,
size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SELECT:{autofocus:null,disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,
placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null}},bc={src:!0,srcset:!0,href:!0,"xlink:href":!0};function cc(a){this.ja=a}cc.prototype.canBind=function(a,b){return void 0!==dc(this,a,b)};
cc.prototype.isResultValid=function(a,b,c){var d=dc(this,a,b);d&&d.alternativeName&&(d=dc(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&Ea(bc,b)){if("srcset"===b){try{var e=Nb(c)}catch(m){return z().error("amp-bind","Failed to parse srcset: ",m),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{b=f[a];var g=d;if(b){if(/__amp_source_origin/.test(b)){b=!1;break a}if(g=g.allowedProtocols)if(b=/^([^:\/?#.]+):[\s\S]*$/.exec(b),null!==b&&!Da.call(g,b[1].toLowerCase().trim())){b=
!1;break a}}b=!0}if(!b)return!1}}var h=d.blacklistedValueRegex;if(c&&h){var n=new RegExp(h,"i");if(n.test(c))return!1}return!0};function dc(a,b,c){if(F(c,"aria-"))return null;if(!Ea(bc,c)||a.ja){var d=Ea(Rb,c);if(void 0!==d)return d;var e=Ea(Sb,c);if(F(b,"AMP-")&&void 0!==e)return e;var f=Ea(ac,b);if(f)return f[c]}};var ec=!1;function fc(a){if(!ec){ec=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(F(g,"--"))f=g;else{Ga||(Ga=D());var h=Ga[g];if(!h){h=g;if(void 0===f[g]){var n=g.charAt(0).toUpperCase()+g.slice(1);b:{for(var m=0;m<Ha.length;m++){var l=Ha[m]+n;if(void 0!==f[l]){n=l;break b}}n=""}void 0!==f[n]&&(h=n)}Ga[g]=h}f=h}f&&(d.style[f]=e)}}};function R(){this.o=[]}R.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};R.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.o.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.o.length)break;if(this.o[d].priority<c)e=d+1;else if(0<d&&this.o[d-1].priority>=c)f=d-1;else break}this.o.splice(d,0,{item:a,priority:b})};R.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
R.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};t.Object.defineProperties(R.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var gc=/nochunking=1/.test(self.location.hash),hc=Promise.resolve();function ic(a,b){if(gc)hc.then(b);else{var c=jc,d=Oa(a),e=M(d);Qa(e,d,"chunk",c);O(a,"chunk").run(b,10)}}function S(a){this.state="not_run";this.S=a}function kc(a,b){if("run"!=a.state){a.state="run";try{a.S(b)}catch(c){throw a.aa(),c;}}}S.prototype.L=function(){return this.S.displayName||this.S.name};S.prototype.aa=function(){};S.prototype.$=function(){return!1};S.prototype.fa=function(){return!0};
function lc(a,b,c){S.call(this,a);var d=this;this.h=b;this.B=null;c.then(function(a){d.B=a;d.B.isVisible()&&kc(d,null);d.B.onVisibilityChanged(function(){d.B.isVisible()&&kc(d,null)})})}ja(lc,S);lc.prototype.aa=function(){fc(self.document)};lc.prototype.$=function(){return this.B?this.B.isVisible():this.h.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.h.location.hash)};lc.prototype.fa=function(){return!!this.B};
function jc(a){var b=this;this.h=a.win;this.J=new R;this.X=this.Y.bind(this);this.ta=Sa(M(a),"viewer");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.Y(null)})}jc.prototype.run=function(a,b){var c=new S(a);mc(this,c,b)};jc.prototype.runForStartup=function(a){a=new lc(a,this.h,this.ta);mc(this,a,Number.POSITIVE_INFINITY)};function mc(a,b,c){a.J.enqueue(b,c);hc.then(function(){nc(a)})}
function oc(a,b){for(var c=a.J.peek();c&&"not_run"!==c.state;)a.J.dequeue(),c=a.J.peek();c&&b&&a.J.dequeue();return c}jc.prototype.Y=function(a){var b=this,c=oc(this,!0);if(!c)return!1;kc(c,a);hc.then(function(){nc(b)});return!0};function pc(a){hc.then(function(){a.X(null)})}function nc(a){var b=oc(a);b&&(b.$()?pc(a):b.fa()&&a.h.requestIdleCallback?qc(a.h,a.X):a.h.postMessage("amp-macro-task","*"))}
function qc(a,b){var c=15;function d(f){if(f.timeRemaining()<c){var g=2E3-(Date.now()-e);0>=g||f.didTimeout?b(f):a.requestIdleCallback(d,{timeout:g})}else b(f)}var e=Date.now();a.requestIdleCallback(d,{timeout:2E3})};function rc(){this.F=D();this.j=null}p=rc.prototype;p.get=function(a){return this.F[a]||null};p.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new Ka,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=D());this.j[a]=b}return b.promise};
p.signal=function(a,b){if(null==this.F[a]){var c=b||Date.now();this.F[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};p.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};p.reset=function(a){this.F[a]&&delete this.F[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function sc(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var h=f;f=null;b.apply(null,h)}}var d=0,e=0,f=null;return function(b){for(var g=[],n=0;n<arguments.length;++n)g[n-0]=arguments[n];e=a.Date.now();f=g;d||(d=a.setTimeout(c,5E3))}};function tc(a,b){for(var c=0,d=0;d<a.length;d++){var e=a[d];b(e,d,a)||(c<d&&(a[c]=e),c++)}c<a.length&&(a.length=c)}function uc(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function vc(a,b,c){var d="ww";b?(b=a.protocol+"//"+a.host,"about:"==a.protocol&&(b=""),a=b+"/dist"):a=ob.cdn;return c?(b=v().singlePassType?v().singlePassType+"/":"",a+"/rtv/"+v().rtvVersion+"/"+b+d+".js"):a+"/"+d+".js"};function wc(a){var b=this;this.h=a;this.ua=N(a,"xhr");var c=a.location,d=!1,e=!d,f=vc(c,d,e);this.W=null;this.Z=this.ua.fetchText(f,{ampCors:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c+"\n//# sourceurl="+f],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.W=new a.Worker(d);b.W.onmessage=b.ra.bind(b)});this.N={};this.la=0;this.ia=[a]}
function xc(a,b,c,d){return a.Z.then(function(){return new Promise(function(e,f){var g=a.la++;a.N[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.ia.indexOf(e);var h=0<=f?f:a.ia.push(e)-1;a.W.postMessage({method:b,args:c,scope:h,id:g})})})}wc.prototype.ra=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.N[b];d?(d.resolve(c),delete this.N[b]):A().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
wc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.N).length};wc.prototype.va=function(){return this.Z};function yc(){var a=zc();return function(b){return setTimeout(b,a())}}function zc(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var U=self.AMPErrors||[];self.AMPErrors=U;function Ac(a){Ac=yc();return Ac(a)}function Bc(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var Cc;
function V(a,b){try{if(a)if(void 0!==a.message)a=Ba(a);else{var c=a;a=Error(Bc(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),v().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&d.oa&&
d.oa("amp:error",a.message);Dc.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function Dc(a,b,c,d,e){var f=this;this&&this.document&&fc(this.document);if(!v().development){var g=!1;try{g=Ec()}catch(n){}if(!(g&&.01<Math.random())){var h=Fc(a,b,c,d,e,g);h&&Ac(function(){return Gc(f,h)})}}}function Gc(a,b){return Hc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",ob.errorReporting,!0);c.send(JSON.stringify(b))}})}
function Hc(a,b){var c=N(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);var d=c.getAmpDoc(),e=d.getRootNode().documentElement,f=e.hasAttribute("report-errors-to-viewer");if(!f)return Promise.resolve(!1);var g=O(d,"viewer");return g.hasCapability("errorReporter")?g.isTrustedViewer().then(function(a){if(!a)return!1;g.sendMessage("error",E({m:b.m,a:b.a,s:b.s,el:b.el,v:b.v,jse:b.jse}));return!0}):Promise.resolve(!1)}
function Fc(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var n=!(self&&self.window),m=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||n)if(h=!0,.001<m)return;var l=0<=a.indexOf("\u200b\u200b\u200b");if(!(l&&.1<m)){g=Object.create(null);g.v=v().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=l?"1":"0";g.ex=h?"1":"0";g.dw=n?"1":"0";var q="1p";self.context&&
self.context.location?(g["3p"]="1",q="3p"):v().runtime&&(q=v().runtime);v().singlePassType&&(g.spt=v().singlePassType);g.rt=q;"inabox"===q&&(g.adid=v().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var k=
self.AMP.viewer.getResolvedViewerUrl(),G=self.AMP.viewer.maybeGetMessagingOrigin();k&&(g.rvu=k);G&&(g.mso=G)}Cc||(Cc=Ic());g.jse=Cc;var C=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var r in f)C.push(r+"="+(f[r]?"1":"0"));g.exps=C.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),l||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document.referrer;g.ae=U.join(",");g.fr=
self.location.originalHash||self.location.hash;b=a;25<=U.length&&U.splice(0,U.length-25+1);U.push(b);return g}}}function Ec(){for(var a=self.document.querySelectorAll("script[src]"),b=0;b<a.length;b++)if(!yb(a[b].src.toLowerCase()))return!0;return!1}
function Ic(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(F(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(F(b,"Error: message"))return"Chrome"}return"unknown"};var Jc="a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" "),
Kc="svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform audio canvas circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan video view vkern".split(" "),Lc="feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" "),
Mc="math menclose merror mfenced mfrac mglyph mi mlabeledtr mmuliscripts mn mo mover mpadded mphantom mroot mrow ms mpspace msqrt mystyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" "),Nc=["#text"],Oc="accept action align alt autocomplete background bgcolor border cellpadding cellspacing checked cite class clear color cols colspan coords crossorigin datetime default dir disabled download enctype face for headers height hidden high href hreflang id integrity ismap label lang list loop low max maxlength media method min multiple name noshade novalidate nowrap open optimum pattern placeholder poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title type usemap valign value width xmlns".split(" "),
Pc="accent-height accumulate additivive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" "),
Qc="accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" "),
Rc=["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"];function W(a,b){for(var c=b.length;c--;)"string"===typeof b[c]&&(b[c]=b[c].toLowerCase()),a[b[c]]=!0;return a}function Sc(a){var b={},c=void 0;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c]);return b}
var Tc=/\{\{[\s\S]*|[\s\S]*\}\}/gm,Uc=/<%[\s\S]*|[\s\S]*%>/gm,Vc=/^data-[\-\w.\u00B7-\uFFFF]/,Wc=/^aria-[\-\w]+$/,Xc=/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,Yc=/^(?:\w+script|data):/i,Zc=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g;u();u();ma();
var $c="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){u();u();u();return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};function X(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}
function ad(){function a(a){var c,e;d("beforeSanitizeAttributes",a,null);var f=a.attributes;if(f){var g={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:w};for(e=f.length;e--;){var ua=c=f[e],h=ua.name,l=ua.namespaceURI;c=c.value.trim();var m=h.toLowerCase();g.attrName=m;g.attrValue=c;g.keepAttr=!0;d("uponSanitizeAttribute",a,g);c=g.attrValue;if("name"===m&&"IMG"===a.nodeName&&f.id){var k=f.id;f=Array.prototype.slice.apply(f);n("id",a);n(h,a);f.indexOf(k)>e&&a.setAttribute("id",k.value)}else if("INPUT"!==
a.nodeName||"type"!==m||"file"!==c||!w[m]&&$a[m])"id"===h&&a.setAttribute(h,""),n(h,a);else continue;if(g.keepAttr&&b(a.nodeName.toLowerCase(),m,c))try{l?a.setAttributeNS(l,h,c):a.setAttribute(h,c),q.removed.pop()}catch(Qd){}}d("afterSanitizeAttributes",a,null)}}function b(a,b,c){if(Tb&&("id"===b||"name"===b)&&(c in y||c in od))return!1;va&&(c=c.replace(Tc," "),c=c.replace(Uc," "));if(!ab||!Vc.test(b))if(!Ub||!Wc.test(b))if(!w[b]||$a[b]||!(Vb[b]||bb.test(c.replace(Zc,""))||("src"===b||"xlink:href"===
b)&&"script"!==a&&0===c.indexOf("data:")&&pd[a]||Wb&&!Yc.test(c.replace(Zc,"")))&&c)return!1;return!0}function c(a){d("beforeSanitizeElements",a,null);if(f(a))return m(a),!0;var b=a.nodeName.toLowerCase();d("uponSanitizeElement",a,{tagName:b,allowedTags:x});if(!x[b]||cb[b]){if(db&&!qd[b]&&"function"===typeof a.insertAdjacentHTML)try{a.insertAdjacentHTML("AfterEnd",a.innerHTML)}catch(Za){}m(a);return!0}!Xb||a.firstElementChild||a.content&&a.content.firstElementChild||!/</g.test(a.textContent)||(q.removed.push({element:a.cloneNode()}),
a.innerHTML=a.innerHTML?a.innerHTML.replace(/</g,"&lt;"):a.textContent.replace(/</g,"&lt;"));va&&3===a.nodeType&&(b=a.textContent,b=b.replace(Tc," "),b=b.replace(Uc," "),a.textContent!==b&&(q.removed.push({element:a.cloneNode()}),a.textContent=b));d("afterSanitizeElements",a,null);return!1}function d(a,b,c){I[a]&&I[a].forEach(function(a){a.call(q,b,c,wa)})}function e(a){return"object"===("undefined"===typeof L?"undefined":$c(L))?a instanceof L:a&&"object"===("undefined"===typeof a?"undefined":$c(a))&&
"number"===typeof a.nodeType&&"string"===typeof a.nodeName}function f(a){return a instanceof fa||a instanceof eb?!1:"string"===typeof a.nodeName&&"string"===typeof a.textContent&&"function"===typeof a.removeChild&&a.attributes instanceof xa&&"function"===typeof a.removeAttribute&&"function"===typeof a.setAttribute?!1:!0}function g(a){return rd.call(a.ownerDocument||a,a,T.SHOW_ELEMENT|T.SHOW_COMMENT|T.SHOW_TEXT,function(){return T.FILTER_ACCEPT},!1)}function h(a){var b=void 0;fb&&(a="<remove></remove>"+
a);if(C)try{b=(new sd).parseFromString(a,"text/html")}catch(Pd){}r&&W(cb,["title"]);if(!b||!b.documentElement){var c=b=gb.createHTMLDocument(""),d=c.body;d.parentNode.removeChild(d.parentNode.firstElementChild);d.outerHTML=a}return td.call(b,ga?"html":"body")[0]}function n(a,b){try{q.removed.push({attribute:b.getAttributeNode(a),from:b})}catch(Za){q.removed.push({attribute:null,from:b})}b.removeAttribute(a)}function m(a){q.removed.push({element:a});try{a.parentNode.removeChild(a)}catch(Od){a.outerHTML=
""}}function l(a){"object"!==("undefined"===typeof a?"undefined":$c(a))&&(a={});x="ALLOWED_TAGS"in a?W({},a.ALLOWED_TAGS):Yb;w="ALLOWED_ATTR"in a?W({},a.ALLOWED_ATTR):Zb;cb="FORBID_TAGS"in a?W({},a.FORBID_TAGS):{};$a="FORBID_ATTR"in a?W({},a.FORBID_ATTR):{};Y="USE_PROFILES"in a?a.USE_PROFILES:!1;Ub=!1!==a.ALLOW_ARIA_ATTR;ab=!1!==a.ALLOW_DATA_ATTR;Wb=a.ALLOW_UNKNOWN_PROTOCOLS||!1;Xb=a.SAFE_FOR_JQUERY||!1;va=a.SAFE_FOR_TEMPLATES||!1;ga=a.WHOLE_DOCUMENT||!1;ha=a.RETURN_DOM||!1;hb=a.RETURN_DOM_FRAGMENT||
!1;$b=a.RETURN_DOM_IMPORT||!1;fb=a.FORCE_BODY||!1;Tb=!1!==a.SANITIZE_DOM;db=!1!==a.KEEP_CONTENT;ya=a.IN_PLACE||!1;bb=a.ALLOWED_URI_REGEXP||bb;va&&(ab=!1);hb&&(ha=!0);Y&&(x=W({},[].concat(X(Nc))),w=[],!0===Y.html&&(W(x,Jc),W(w,Oc)),!0===Y.svg&&(W(x,Kc),W(w,Pc),W(w,Rc)),!0===Y.svgFilters&&(W(x,Lc),W(w,Pc),W(w,Rc)),!0===Y.mathMl&&(W(x,Mc),W(w,Qc),W(w,Rc)));a.ADD_TAGS&&(x===Yb&&(x=Sc(x)),W(x,a.ADD_TAGS));a.ADD_ATTR&&(w===Zb&&(w=Sc(w)),W(w,a.ADD_ATTR));a.ADD_URI_SAFE_ATTR&&W(Vb,a.ADD_URI_SAFE_ATTR);db&&
(x["#text"]=!0);ga&&W(x,["html","head","body"]);x.table&&W(x,["tbody"]);Object&&"freeze"in Object&&Object.freeze(a);wa=a}function q(a){return ad(a)}var k=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;q.version="1.0.8";q.removed=[];if(!k||!k.document||9!==k.document.nodeType)return q.isSupported=!1,q;var G=k.document,C=!1,r=!1,y=k.document,J=k.DocumentFragment,L=k.Node,T=k.NodeFilter,K=k.NamedNodeMap,xa=void 0===K?k.NamedNodeMap||k.MozNamedAttrMap:K,
fa=k.Text,eb=k.Comment,sd=k.DOMParser;"function"===typeof k.HTMLTemplateElement&&(K=y.createElement("template"),K.content&&K.content.ownerDocument&&(y=K.content.ownerDocument));var za=y,gb=za.implementation,rd=za.createNodeIterator,td=za.getElementsByTagName,ud=za.createDocumentFragment,vd=G.importNode,I={};q.isSupported=gb&&"undefined"!==typeof gb.createHTMLDocument&&9!==y.documentMode;var bb=Xc,x=null,Yb=W({},[].concat(X(Jc),X(Kc),X(Lc),X(Mc),X(Nc))),w=null,Zb=W({},[].concat(X(Oc),X(Pc),X(Qc),X(Rc))),
cb=null,$a=null,Ub=!0,ab=!0,Wb=!1,Xb=!1,va=!1,ga=!1,ib=!1,fb=!1,ha=!1,hb=!1,$b=!1,Tb=!0,db=!0,ya=!1,Y={},qd=W({},"audio head math script style template svg video".split(" ")),pd=W({},["audio","video","img","source","image"]),Vb=W({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),wa=null,od=y.createElement("form");q.isSupported&&(function(){try{h('<svg><p><style><img src="</style><img src=x onerror=alert(1)//">').querySelector("svg img")&&(C=!0)}catch(ua){}}(),
function(){try{h("<x/><title>&lt;/title&gt;&lt;img&gt;").querySelector("title").textContent.match(/<\/title/)&&(r=!0)}catch(ua){}}());var wd=function Za(b){var e=void 0,f=g(b);for(d("beforeSanitizeShadowDOM",b,null);e=f.nextNode();)d("uponSanitizeShadowNode",e,null),c(e)||(e.content instanceof J&&Za(e.content),a(e));d("afterSanitizeShadowDOM",b,null)};q.sanitize=function(b,d){var f=void 0,n=void 0,C=void 0,r=void 0;b||(b="\x3c!--\x3e");if("string"!==typeof b&&!e(b)){if("function"!==typeof b.toString)throw new TypeError("toString is not a function");
b=b.toString();if("string"!==typeof b)throw new TypeError("dirty is not a string, aborting");}if(!q.isSupported){if("object"===$c(k.toStaticHTML)||"function"===typeof k.toStaticHTML){if("string"===typeof b)return k.toStaticHTML(b);if(e(b))return k.toStaticHTML(b.outerHTML)}return b}ib||l(d);q.removed=[];if(!ya)if(b instanceof L)f=h("\x3c!--\x3e"),n=f.ownerDocument.importNode(b,!0),1===n.nodeType&&"BODY"===n.nodeName?f=n:f.appendChild(n);else{if(!ha&&!ga&&-1===b.indexOf("<"))return b;f=h(b);if(!f)return ha?
null:""}f&&fb&&m(f.firstChild);for(var w=g(ya?b:f);d=w.nextNode();)3===d.nodeType&&d===C||c(d)||(d.content instanceof J&&wd(d.content),a(d),C=d);if(ya)return b;if(ha){if(hb)for(r=ud.call(f.ownerDocument);f.firstChild;)r.appendChild(f.firstChild);else r=f;$b&&(r=vd.call(G,r,!0));return r}return ga?f.outerHTML:f.innerHTML};q.setConfig=function(a){l(a);ib=!0};q.clearConfig=function(){wa=null;ib=!1};q.isValidAttribute=function(a,c,d){wa||l({});return b(a.toLowerCase(),c.toLowerCase(),d)};q.addHook=function(a,
b){"function"===typeof b&&(I[a]=I[a]||[],I[a].push(b))};q.removeHook=function(a){I[a]&&I[a].pop()};q.removeHooks=function(a){I[a]&&(I[a]=[])};q.removeAllHooks=function(){I={}};return q};ad()(self);E({input:{type:/(?:image|button)/i}});var bd="form formaction formmethod formtarget formnovalidate formenctype".split(" ");E({input:bd,textarea:bd,select:bd});function cd(a,b,c){var d=self.location;Bb(c);var e=yb(d),f=Q(zb(d));if("href"==b&&!F(c,"#"))return Ab(c,f);if("src"==b)return"amp-img"==a?dd(c,f,e):Ab(c,f);if("srcset"==b){try{var g=Nb(c)}catch(h){return z().error("purifier","Failed to parse srcset: ",h),c}return g.stringify(function(a){return dd(a,f,e)})}return c}
function dd(a,b,c){a=Q(Ab(a,b));return"data:"==a.protocol||yb(a)||!c?a.href:ob.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};function ed(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function fd(a,b){var c=ed,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}}function gd(a){return new Promise(function(b){fd(a,b)})};var hd=/^(i?-)?amp(html)?-/,id=D({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state","is-layout-container"],"AMP-SELECTOR":["selected"]});
function jd(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.G=b||a.win;this.R=[];this.pa=sc(this.h,function(){c.R.length=0});this.C=[];this.D=D();this.T=O(a,"history");this.ba=[];this.H=1E3;this.da=O(a,"resources");this.w=D();this.sa=N(this.h,"timer");this.ga=null;this.B=O(this.ampdoc,"viewer");this.B.onMessageRespond("premutate",this.qa.bind(this));this.M=this.B.whenFirstVisible().then(function(){if(b){var c=b.document;return gd(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})}).then(function(a){return c.U(a)});
this.O=null;this.ea=new rc;var d=self.AMP;d.printState=d.printState||this.na.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.ma.bind(this)}jd.installInEmbedWindow=function(a,b){Pa(a,new jd(b,a))};p=jd.prototype;p.signals=function(){return this.ea};
p.setState=function(a,b,c){var d=this;try{Fa(this.w,a)}catch(e){z().error("amp-bind","Failed to merge result from AMP.setState().",e)}A().info("amp-bind","state:",this.w);return b?Promise.resolve():this.O=this.M.then(function(){return kd(d)}).then(function(a){return ld(d,a,c)})};
p.invoke=function(a){var b=a,c=b.args,d=b.event,e=b.method,f=b.sequenceId,g=b.tagOrTarget;if(this.R.includes(f))return z().error("amp-bind","One state action allowed per event."),Promise.resolve();this.R.push(f);this.pa();if(b=c.__AMP_OBJECT_STRING__)switch(this.H=Math.min(2E3,Math.max(1E3,this.H+500)),this.ea.signal("FIRST_MUTATE"),c={},d&&d.detail&&(c.event=d.detail),e){case "setState":return this.setStateWithExpression(b,c);case "pushState":return this.pushStateWithExpression(b,c);default:return Promise.reject(A().createError("Unrecognized method: %s.%s",
g,e))}else z().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return Promise.resolve()};p.setStateWithExpression=function(a,b){var c=this;A().info("amp-bind","setState:",'"'+a+'"');return this.O=md(this,a,b).then(function(a){return c.setState(a)}).then(function(){c.T.replace({data:E({"amp-bind":c.w}),title:c.G.document.title})})};
p.pushStateWithExpression=function(a,b){var c=this;A().info("amp-bind","pushState:",a);return md(this,a,b).then(function(a){function b(){return c.setState(d)}var d=D();Object.keys(a).forEach(function(a){a:{var b=c.w[a];if(void 0!==b)try{var e=JSON.parse(JSON.stringify(b));break a}catch(m){A().error("amp-bind","Failed to copy JSON ("+b+") with error: "+m)}e=null}d[a]=e});return c.setState(a).then(function(){c.T.push(b,{data:E({"amp-bind":c.w}),title:c.G.document.title})})})};
p.scanAndApply=function(a,b,c){function d(a){nd(e,b).then(function(b){A().info("amp-bind","\u2937","\u0394:",a-b,", \u2211:",e.numberOfBindings())});return Promise.resolve()}var e=this;c=void 0===c?2E3:c;A().info("amp-bind","rescan:",a,b);if(this.numberOfBindings()>this.H)return xd(this),d(0);var f=[],g=a.slice();a.forEach(function(a){Array.prototype.push.apply(g,a.querySelectorAll("[i-amphtml-binding]"))});g.forEach(function(a){yd(e,a,Number.POSITIVE_INFINITY,f)});var h=f.length;if(0===h)return d(0);
var n=zd(this,f).then(function(){return kd(e).then(function(b){return Ad(e,b,a)})}).then(function(){d(h)});return this.sa.timeoutPromise(c,n,"Timed out waiting for amp-bind to process rendered template.")};p.getStateValue=function(a){a=Cb(this.w,a);return Aa(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
p.U=function(a){var b=this;A().info("amp-bind","init");var c=!Bd(this);this.ga=new cc(c);return Z(this,"bind.init",[c]).then(function(){return Promise.all([Cd(b),Dd(b,[a])])}).then(function(c){A().info("amp-bind","\u2937","\u0394:",c);a.addEventListener("amp:dom-update",function(a){return Ed(b,a)});if(v().development)return kd(b).then(function(a){return Fd(b,a)})}).then(function(){b.B.sendMessage("bindReady",void 0)})};
function Bd(a){a=a.G.document.documentElement;var b=a.hasAttribute("amp4email")||a.hasAttribute("\u26a14email");return b}p.numberOfBindings=function(){return this.C.reduce(function(a,b){return a+b.boundProperties.length},0)};p.ya=function(a){this.H=a};p.wa=function(){return this.T};
p.qa=function(a){var b=this,c=[];return this.M.then(function(){Object.keys(a.state).forEach(function(d){b.ba.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&z().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};p.makeStateKeyOverridable=function(a){this.ba.push(a)};
function Cd(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];Xa(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Gd(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Dd(a,b){var c=b.map(function(b){var c=a.H-a.numberOfBindings();return Hd(a,b,c).then(function(b){var c=b.bindings,d=b.limitExceeded;d&&xd(a);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?zd(a,b):0})}function xd(a){A().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.H)}
function zd(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.D[b];0<d.length&&Gd(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function nd(a,b){tc(a.C,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];tc(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Hd(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();var d=c-e.length;yd(a,b,d,e)&&(g=!0);return!f.nextNode()||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var l=!1;if(f&&!f.didTimeout)for(;1<f.timeRemaining()&&!l;)l=d();else{var h=250;for(f=0;f<h&&!l;f++)l=d()}l?b({bindings:e,limitExceeded:g}):ic(a.ampdoc,c)}ic(a.ampdoc,
c)})}function yd(a,b,c,d){var e=!1,f=Id(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.C.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c,f=e.expressionString;d.push({tagName:g,property:e.property,expressionString:f});a.D[f]||(a.D[f]=[]);a.D[f].push(b)});return e}
function Id(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,h=a,n=d[e];var m=b;var l=m.tagName,q=n.name;if(2<q.length&&"["===q[0]&&"]"===q[q.length-1])g=q.substr(1,q.length-2);else if(F(q,"data-amp-bind-")&&(g=q.substr(14),m.hasAttribute("["+g+"]"))){m=null;break a}if(g){if(h.ga.canBind(l,g)){m={property:g,expressionString:n.value};break a}g=z().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,l);V(g,m)}m=null}m&&c.push(m)}return c}
function md(a,b,c){return a.M.then(function(){Object.assign(c,a.w);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Gd(a,"amp-bind: Expression eval failed.");A().info("amp-bind","\u2937",b);return b})}
function kd(a){var b=Z(a,"bind.evaluateBindings",[a.w]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.D[b];if(0<c.length){var d=e[b],f=z().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,d.message);f.stack=d.stack;V(f,c[0])}});A().info("amp-bind","bindings:",c);return c})}
function Fd(a,b){var c=void 0===c?null:c;var d=void 0===d?!0:d;var e={};a.C.forEach(function(a){var f=a.element;a=a.boundProperties;c&&!Jd(c,f)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var g=a.property,l=id[f.tagName];if(l&&l.includes(g))c=null;else{switch(g){case "text":g=f.textContent;c=String(c);l=g.trim()===c.trim();break;case "class":g=[];for(l=0;l<f.classList.length;l++){var h=f.classList[l];hd.test(h)||g.push(h)}h=[];Array.isArray(c)?h=c:"string"===typeof c?(l=c.trim(),
0<l.length&&(h=l.split(" "))):(l=z().createError('%s: "%s" is not a valid result for [class].',"amp-bind",c),V(l,f));b:{l=g;var k=h;if(l.length!==k.length)l=!1;else{h=(Array.isArray(l)?l:l?Array.prototype.slice.call(l):[]).sort();k=(Array.isArray(k)?k:k?Array.prototype.slice.call(k):[]).sort();for(var G=0;G<l.length;G++)if(h[G]!==k[G]){l=!1;break b}l=!0}}break;default:g=f.getAttribute(g),l=!0===c?""===g:!1===c?null===g:g===c}c=l?null:{expected:c,actual:g}}var C=c;if(C){c=f.tagName;g=a.property;a=
a.expressionString;l=C;h=l.expected;var r=l.actual;e[c+"["+g+"]"+h+":"+r]=!0;d&&z().warn("amp-bind","Default value ("+r+") does not match first "+("result ("+h+") for <"+c+" ["+g+']="')+(a+'">. We recommend writing expressions with ')+"matching default values, but this can be safely ignored if intentional.")}}})});return Object.keys(e)}function Jd(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function Kd(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||Eb(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function ld(a,b,c){var d=a.C.map(function(d){return c&&"AMP-STATE"==d.element.tagName?Promise.resolve():Ld(a,b,d)});return Promise.all(d).then(function(){A().info("amp-bind","updated:",d.length,"elements")})}
function Ad(a,b,c){var d=[];a.C.forEach(function(e){c.forEach(function(c){c.contains(e.element)&&d.push(Ld(a,b,e))})});return Promise.all(d).then(function(){A().info("amp-bind","updated:",d.length,"elements")})}
function Ld(a,b,c){var d=c.element,e=Kd(c.boundProperties,b);return 0===e.length?Promise.resolve():a.da.mutateElement(d,function(){var b=D(),c,h;e.forEach(function(e){var f=e,g=f.boundProperty;f=f.newValue;a:{var k=g.property;var n=d.tagName;switch(k){case "text":k=!0;var m=String(f);"TEXTAREA"===n&&(d.value=m,k=!1);"TITLE"===n&&d.parentNode===a.G.document.head&&(a.G.document.title=m);k&&(d.textContent=m);break;case "class":k=[];for(m=0;m<d.classList.length;m++){var r=d.classList[m];hd.test(r)&&k.push(r)}Array.isArray(f)||
"string"===typeof f?d.setAttribute("class",k.concat(f).join(" ")):null===f?d.setAttribute("class",k.join(" ")):(k=z().createError('%s: "%s" is not a valid result for [class].',"amp-bind",f),V(k,d));break;default:n="INPUT"==n&&k in d;var y=d.getAttribute(k),J=!1;if("boolean"===typeof f)n&&d[k]!==f&&(d[k]=f,J=!0),f&&""!==y?(d.setAttribute(k,""),J=!0):f||null===y||(d.removeAttribute(k),J=!0);else if(f!==y)b:{y=String(f);try{m=d.tagName.toLowerCase();r=k.toLowerCase();var L="src"==r||"href"==r||"srcset"==
r?cd(m,r,y):y;if(yb(self.location)&&"a"===m&&"href"===r){var T=d.getAttribute(r),K="#"===L[0],xa=T&&"#"===T[0];K&&!xa?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):xa&&!K&&d.setAttribute("target",d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}n&&(d[r]=L);d.setAttribute(r,L);J=!0;break b}catch(eb){m=z().createError('%s: "%s" is not a valid result for [%]',"amp-bind",y,k,eb),V(m,d)}J=!1}if(J){k={name:k,value:f};break a}}k=null}var fa=
k;fa&&(b[fa.name]=fa.value,g=g.property,"width"==g?c="number"===typeof f&&isFinite(f)?Number(f):c:"height"==g&&(h="number"===typeof f&&isFinite(f)?Number(f):h))});void 0===c&&void 0===h||a.da.changeSize(d,h,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(m){var n=z().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(b),m);V(n,d)}})}
function Ed(a,b){b=b.target;var c=b.parentNode;c&&"AMP-LIST"==c.tagName||(A().info("amp-bind","dom_update:",b),Md(a,[b],[b]).then(function(){}))}function Md(a,b,c){var d=0;return nd(a,b).then(function(b){d=b;return Dd(a,c)}).then(function(b){A().info("amp-bind","\u2937","\u0394:",b-d,", \u2211:",a.numberOfBindings());return{added:b,removed:d}})}
function Z(a,b,c){var d=a.h;a=a.G;if(d.Worker){var e=Ma(d);Qa(e,e,"amp-worker",wc);d=N(d,"amp-worker");b=xc(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Gd(a,b,c){b=z().createError("%s %s",b,a.message);b.stack=a.stack;V(b,c);return b}
p.na=function(a){if(a)if("string"==typeof a){var b=Cb(this.w,a);z().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=z().assertElement(a),Nd(this,b)):z().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else z().info("amp-bind",this.w)};
function Nd(a,b){var c=uc(a.C,function(a){return a.element==b});if(0>c)z().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.C[c].boundProperties;e.forEach(function(b){d.push(md(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=D();e.forEach(function(c,d){b[c.property]=a[d]});z().info("amp-bind",b)})}}p.ma=function(a){md(this,a,this.w).then(function(a){z().info("amp-bind",a)})};p.xa=function(){return this.M};p.za=function(){return this.O};(function(a){a.registerServiceForDoc("bind",jd);a.registerElement("amp-state",Hb);a.registerElement("amp-bind-macro",Ja)})(self.AMP);
})});
//# sourceMappingURL=amp-bind-0.1.js.map

